#!/usr/bin/env python3
import os
import sys
(num_mb_as_str,) = sys.argv[1:]
num_mb = int(num_mb_as_str) // 2
(rpipe, wpipe) = os.pipe()
while num_mb > 0:
    input('Press return to consume %d MB: ' % (num_mb,))
    if os.fork() > 0:
        num_mb = num_mb // 2
        continue
    try:
        os.close(wpipe)
        x = os.urandom(num_mb * 1048576)
        os.read(rpipe, 1)
    finally:
        os._exit(0)
input('Press return to exit: ')
